spring:
  application:
    name: linshen-dubbo-consumer1
server:
  port: 8081

dubbo:
  application:
    id: dubbo-client1
    name: dubbo-client1
  registry:
    protocol: zookeeper
    address: localhost:2181
    id: dubbo
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'